#!/bin/sh
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
        build-essential \
        software-properties-common \
        kmod \ 
        snapd \
        sudo 
RUN add-apt-repository -y ppa:morphis/anbox-support
RUN apt update
RUN apt install snapd
#apt install anbox-modules-dkms
#docker run -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw"  -v /mnt/store/android_images:/var/lib/anbox/ --privileged  -v /tmp/.X11-unix:/tmp/.X11-unix local:fast_anbox /bin/bash