FROM dmeyerson/anbox:latest
COPY start_anbox.sh start_anbox.sh
ENTRYPOINT ["/anbox/start_anbox.sh"]
#CMD ["ps", "-A"] # default command - used if user does not provide one

# #ip link add dev "${BRIDGE}" type bridge
# # logs    
# 12  cat /var/lib/anbox/logs/container.log 
# 13  cat /var/lib/anbox/logs/console.log 

#mount |grep cgroup

#,cpuset,cpu